import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import countries from 'world-countries'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Build countries array as main data source
const countriesArray = []
const alpha3Lookup = {}
const numericLookup = {}

countries.forEach((c) => {
  const country = {
    alpha2: c.cca2,
    name: c.name.common,
  }

  if (c.cca3) {
    country.alpha3 = c.cca3
    alpha3Lookup[c.cca3] = c.cca2
  }

  if (c.ccn3) {
    const numKey = c.ccn3.padStart(3, '0')
    country.numeric = numKey
    numericLookup[numKey] = c.cca2
  }

  countriesArray.push(country)
})

// Sort countries by name for easier use in dropdowns
countriesArray.sort((a, b) => a.name.localeCompare(b.name))

// Format object as multi-line for readability
const formatObj = (obj, indent = 2, quoteKeys = false) => {
  const entries = Object.entries(obj)
  const lines = []
  let line = ''

  entries.forEach(([k, v]) => {
    const key = quoteKeys ? `'${k}'` : k
    const pair = `${key}: '${v}'`
    if (line.length + pair.length > 75) {
      lines.push(line.slice(0, -1)) // remove trailing space
      line = ''
    }
    line += pair + ', '
  })
  if (line) lines.push(line.slice(0, -2)) // remove trailing comma and space

  return lines.map((l) => ' '.repeat(indent) + l).join('\n')
}

// Format countries array
const formatCountriesArray = (countries, indent = 2) => {
  const lines = []
  countries.forEach((c) => {
    const parts = [`alpha2: '${c.alpha2}'`]
    if (c.alpha3) parts.push(`alpha3: '${c.alpha3}'`)
    if (c.numeric) parts.push(`numeric: '${c.numeric}'`)
    parts.push(`name: ${JSON.stringify(c.name)}`)
    const objStr = `{ ${parts.join(', ')} }`
    lines.push(' '.repeat(indent) + objStr + ',')
  })
  return lines.join('\n')
}

const content = `// Auto-generated by scripts/genCountryLookup.js
// Country data with lookup helpers

export type Country = {
  alpha2: string
  alpha3?: string
  numeric?: string
  name: string
}

// Main countries array (sorted by name)
export const countries: Country[] = [
${formatCountriesArray(countriesArray)}
]

// Alpha-3 (ISO 3166-1 alpha-3) to Alpha-2 (ISO 3166-1 alpha-2)
const alpha3: Record<string, string> = {
${formatObj(alpha3Lookup)}
}

// Numeric (ISO 3166-1 numeric) to Alpha-2
const numeric: Record<string, string> = {
${formatObj(numericLookup, 2, true)}
}

export const getAlphaTwoCode = (code: string | number): string => {
  const uc = String(code).toUpperCase()
  // Try alpha-3 lookup
  if (uc.length === 3 && alpha3[uc]) return alpha3[uc]
  // Try numeric lookup (with zero padding for numbers)
  const numKey = uc.padStart(3, '0')
  if (numeric[numKey]) return numeric[numKey]
  // Return as-is (already alpha-2 or special code like GB-ENG)
  return uc
}

export const getCountryByAlpha2 = (code: string): Country | undefined => {
  const uc = String(code).toUpperCase()
  return countries.find((c) => c.alpha2 === uc)
}

export const getCountryByAlpha3 = (code: string): Country | undefined => {
  const uc = String(code).toUpperCase()
  return countries.find((c) => c.alpha3 === uc)
}

export const getCountryByNumeric = (code: string | number): Country | undefined => {
  const numKey = String(code).padStart(3, '0')
  return countries.find((c) => c.numeric === numKey)
}
`

const target = path.resolve(__dirname, '../src/country.ts')
fs.writeFileSync(target, content)
console.log(`Generated ${target}`)
