import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import countries from 'world-countries'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Build lookup tables
const alpha3 = {}
const numeric = {}

countries.forEach((c) => {
  if (c.cca3) alpha3[c.cca3] = c.cca2
  if (c.ccn3) numeric[c.ccn3.padStart(3, '0')] = c.cca2
})

// Format object as multi-line for readability
const formatObj = (obj, indent = 2, quoteKeys = false) => {
  const entries = Object.entries(obj)
  const lines = []
  let line = ''

  entries.forEach(([k, v]) => {
    const key = quoteKeys ? `'${k}'` : k
    const pair = `${key}: '${v}'`
    if (line.length + pair.length > 75) {
      lines.push(line.slice(0, -1)) // remove trailing space
      line = ''
    }
    line += pair + ', '
  })
  if (line) lines.push(line.slice(0, -2)) // remove trailing comma and space

  return lines.map((l) => ' '.repeat(indent) + l).join('\n')
}

const content = `// Auto-generated by scripts/genCountryLookup.js
// Minimal lookup tables for country code conversion

// Alpha-3 (ISO 3166-1 alpha-3) to Alpha-2 (ISO 3166-1 alpha-2)
const alpha3: Record<string, string> = {
${formatObj(alpha3)}
}

// Numeric (ISO 3166-1 numeric) to Alpha-2
const numeric: Record<string, string> = {
${formatObj(numeric, 2, true)}
}

export const getAlphaTwoCode = (code: string | number): string => {
  const uc = String(code).toUpperCase()
  // Try alpha-3 lookup
  if (uc.length === 3 && alpha3[uc]) return alpha3[uc]
  // Try numeric lookup (with zero padding for numbers)
  const numKey = uc.padStart(3, '0')
  if (numeric[numKey]) return numeric[numKey]
  // Return as-is (already alpha-2 or special code like GB-ENG)
  return uc
}
`

const target = path.resolve(__dirname, '../src/country.ts')
fs.writeFileSync(target, content)
console.log(`Generated ${target}`)
